version: '2.3'
services:
  formplayer:
    image: dimagi/formplayer
    environment:
      COMMCARE_HOST: "http://host.docker.internal:8000"
      COMMCARE_ALTERNATE_ORIGINS: "http://localhost:8000,http://127.0.0.1:8000"
      AUTH_KEY: "secretkey"
      EXTERNAL_REQUEST_MODE: "replace-host"
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
      - "8081:8081"

  postgres:
    extends:
      file: "${COMPOSE_ARCH}"
      service: postgres
    environment:
      POSTGRES_USER: commcarehq
      POSTGRES_PASSWORD: commcarehq
    ports:
      - "5432:5432"
    volumes:
      - ${VOLUME_PREFIX}${BLANK_IF_TESTS-postgresql:}/var/lib/postgresql/data

  couch:
    image: dimagi/couchdb-dev:3.1.1
    command: ["--with-haproxy", "--with-admin-party-please", "-n", "1"]
    ulimits:
      # fix high CPU usage (1048576 is the default, tried 65536, 1024 fixed it)
      # https://groups.google.com/forum/#!topic/rabbitmq-users/hO06SB-QBqc
      nofile:
        soft: 1024
        hard: 1048576
    ports:
      - "5984:5984"
    volumes:
      - ${VOLUME_PREFIX}${BLANK_IF_TESTS-couchdb2:}/usr/src/couchdb/dev/lib/node1/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ${VOLUME_PREFIX}${BLANK_IF_TESTS-redis:}/data

  elasticsearch2:
    image: elasticsearch:2.4.6
    command: elasticsearch --cluster.name=${ES_CLUSTER_NAME}
    environment:
      ES_CLUSTER_NAME: ${ES_CLUSTER_NAME}
      ES_JAVA_OPTS: "-Des.script.engine.groovy.inline.aggs=true -Des.script.engine.groovy.inline.search=true"
    ports:
      - "9200:9200"
    volumes:
      - ${VOLUME_PREFIX}${BLANK_IF_TESTS-elasticsearch2:}/usr/share/elasticsearch/data
      - ./files/elasticsearch_2.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw

  elasticsearch5:
    image: elasticsearch:5.6.16
    command: elasticsearch
    environment:
      ES_CLUSTER_NAME: ${ES_CLUSTER_NAME}
      ES_JAVA_OPTS: "-Xms750m -Xmx750m -Des.script.engine.groovy.inline.aggs=true -Des.script.engine.groovy.inline.search=true"
    ports:
      - "9205:9200"
    volumes:
      - ${VOLUME_PREFIX}${BLANK_IF_TESTS-elasticsearch5:}/usr/share/elasticsearch/data
      - ./files/elasticsearch_5.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ${VOLUME_PREFIX}${BLANK_IF_TESTS-zookeeper:}/opt/zookeeper-3.4.13/data

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME:-kafka}
      KAFKA_ADVERTISED_PORT: 9092
      CUSTOM_INIT_SCRIPT: |
        URL="https://raw.githubusercontent.com/vishnubob/wait-for-it/c096cface5fbd9f2d6b037391dfecae6fde1362e/wait-for-it.sh"
        if curl --max-time 10 \$URL > wait.sh ; then
          chmod +x ./wait.sh
          ./wait.sh -t 30 zookeeper:2181 || exit 1
        else
          echo "Wait script download failed"
        fi
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:${DOCKER_SOCK:-/var/run/docker.sock}
      - ${VOLUME_PREFIX}${BLANK_IF_TESTS-kafka:}/kafka/kafka-logs-1

  minio:
    image: minio/minio
    command: server --address :9980 /data
    ports:
      - "9980:9980"
    volumes:
      - ${VOLUME_PREFIX}${BLANK_IF_TESTS-minio-conf:}/root/.minio
      - ${VOLUME_PREFIX}${BLANK_IF_TESTS-minio-data:}/data
    environment:
      MINIO_ACCESS_KEY: admin-key
      MINIO_SECRET_KEY: admin-secret
