########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud --control staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/GTD/Deploy+Process#DeployProcess-vellum
    - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
    # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
    # - sr/es-alias # Sravan Nov 18
    - ce/bulk-case-search # Cal July 6
    # - sr/memoized-toggle # Sravan July 26
    # - dependabot/pip/requirements/certifi-2021.10.8   # SK / Joel Oct 12
    # - mk/support-expanded-cols-in-mobile-ucr # MK Feb 2
    - mjr/all_safe_fixes  # Matt May 11
    - bmb/sso/api/test-001  # Biyeun June 15
    - mjr/report-logging-verification # Matt July 20
    - ml/limit-superuser-changes # Minha July 25
    - bmb/pyopenssl-upgrade-22.0.0  # Biyeun Aug 22 (impacts SSO)
    # - ad/remove-entered-wrap-functions # Addison Aug 22
    - ce/api-rate-limits # Cal Aug 23
    - dmr/add-support-for-ses-django-email-backend  # Danny Aug 26
    - do/migrate-apps # Dominic Sep 2
    # - akj/abdm-api # Akash Sep 5
    # - sk/webapps-update-url # Simon Sep 13
    - ap/sql-repeater/phase-2 # Amit Sep 16
    - smh/remove-setSelectedValue-import # Steph Sept 20
    - rc/update-case-search-settings-mapping # Robert Sept 20
    - rp/mobile-worker-validation # Rynhard Sept 21
    # - jt/ush-2147_improve_print_css #Jonathan T. Sept 22
    # - mp/mobile_fix-2fa # Marco Sep 26
    - dm/sql-lookup-tables-pr2 # Daniel Sept 27
    - jls/new-instance-connectors # Jenny Sept 27
    - jls/cloudcare-drop-datatables # Jenny Sept 29
    - akj/abdm-api-for-mobile-app # Akash Sep 28
    - dependabot/pip/requirements/jwcrypto-1.4  # Biyeun Sep 28 (OIDC)
    - bmb/remove-oidc-dev-notice  # Biyeun Sep 29
    - gh/replace-base-crud-view # Graham Sep 29
    - jls/standardize-web-apps-js-imports # Jenny Oct 3
    - akj/release-mode-toggle # Akash 7 Oct
    - smh/multi-select-selection-update # Steph Oct 10
submodules: { }
